server:
  port: 4085

spring:
  application:
    name: USER-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

data:
  exception:
    message1: UserResourceException
    message2: NotFound this Id
    message3: DataConnectivityisLost