server:
  port: 4084

spring:
  application:
    name: PRODUCT-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:4086/eureka/
  instance:
    hostname: localhost

