server:
  port: 4084

spring:
  application:
    name: PRODUCT-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

data:
  exception:
    message1: ProductResourceException
    message2: Not found Product with id
    message3: DataConnectivityisLost